### ISSUE TITLE
Avatar by UUID

### ISSUE THREAD

**Issue by Carlosjrlu** [elyby/chrly#30]
Is there any way to get the avatar (head 2d image) of a player's skin by their username or uuid on png from the ely.by skinsystem database?

Like for example this [link](https://crafatar.com/avatars/069a79f444e94726a5befca90e38aaf5) gives me this image:
![Notch](https://user-images.githubusercontent.com/20954701/107904256-448eb200-6f19-11eb-8090-abb7c7dcf83e.png)

**Comment by erickskrauch** [comment]
The Chrly service isn't responsible for rendering previews of skins. Nevertheless, it makes sense to move away from using integer IDs in v5 and use the UUID-username hash, which will allow giving textures by username as well as by UUID.

**Comment by Carlosjrlu** [comment]
Yeah, I found the SkinRenderer2D repository that seems to be responsible for rendering preview, and manage to find the link for avatar heads:
https://ely.by/services/skins-renderer?url=http://skinsystem.ely.by/skins/Notch.png&scale=18.9&renderFace=1

**Comment by erickskrauch** [comment]
Yes, that's right. For now, we use this service for internal needs, but its API is stable and we plan to make it publicly available in the future by removing the restriction of only Ely.by's domains.

**Comment by jukixyo** [comment]
but uhh what to do with the uuid one
