### ISSUE TITLE
Skin system for proxy server isn't functioning at all.

### ISSUE THREAD

**Issue by Clyde6790pGIT** [elyby/chrly#41]
![Screenshot 2024-05-28 185230](https://github.com/elyby/chrly/assets/78290310/ced8602c-04f8-4590-9858-a260a74689b1)
Other players who aren't ely.by users cannot see your skin, I have installed the server plugin just so it would allow everyone to see each other but it seems to not function at all.
I have tried using it on the backend servers only (Paper)
and the proxy server (Velocity with Snap! BungeeCord to Velocity plugin translator)
I have also gave the plugin an auth key.

**Comment by erickskrauch** [comment]
To be honest, we haven't tested our plugin on new versions of Minecraft or new server cores. Our plugin is infinitely outdated and I don't have anyone to work on it :( You can try an [alternative open-source plugin](https://git.kaydax.xyz/Kaydax/openely), which may work for you.

**Comment by Clyde6790pGIT** [comment]
Ok, thanks for informing me, I am fairly new to server setups so I didn't know this was deprecated.
